// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://tujvvgthiheceksfpnql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1anZ2Z3RoaWhlY2Vrc2ZwbnFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDIzNTEsImV4cCI6MjA3NDIxODM1MX0.lZa1BTOKOAzIPg70yZ21akeE_1lQqv3nAghefoovbVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);